//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 10:06:28 AM EET 
//


package com.cosmote.api.generic.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cosmote.api.generic.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatusCode_QNAME = new QName("http://www.accenture.com/assets/sdp/commonDataModel/asynch", "statusCode");
    private final static QName _ErrorCode_QNAME = new QName("http://www.accenture.com/assets/sdp/commonDataModel/asynch", "errorCode");
    private final static QName _ErrorDescription_QNAME = new QName("http://www.accenture.com/assets/sdp/commonDataModel/asynch", "errorDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cosmote.api.generic.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncomingRequest }
     * 
     */
    public IncomingRequest createIncomingRequest() {
        return new IncomingRequest();
    }

    /**
     * Create an instance of {@link TSODATA }
     * 
     */
    public TSODATA createTSODATA() {
        return new TSODATA();
    }

    /**
     * Create an instance of {@link TSOheader }
     * 
     */
    public TSOheader createTSOheader() {
        return new TSOheader();
    }

    /**
     * Create an instance of {@link TSOattributes }
     * 
     */
    public TSOattributes createTSOattributes() {
        return new TSOattributes();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link TSOresult }
     * 
     */
    public TSOresult createTSOresult() {
        return new TSOresult();
    }

    /**
     * Create an instance of {@link ApplicationResponse }
     * 
     */
    public ApplicationResponse createApplicationResponse() {
        return new ApplicationResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch", name = "statusCode")
    public JAXBElement<String> createStatusCode(String value) {
        return new JAXBElement<String>(_StatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch", name = "errorCode")
    public JAXBElement<String> createErrorCode(String value) {
        return new JAXBElement<String>(_ErrorCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch", name = "errorDescription")
    public JAXBElement<String> createErrorDescription(String value) {
        return new JAXBElement<String>(_ErrorDescription_QNAME, String.class, null, value);
    }

}
