//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.29 at 08:13:36 PM EEST 
//


package com.cosmote.api.generic.xjc;

import java.util.ArrayList;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}attribute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}list" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute",
    "list"
})
@XmlRootElement(name = "TSOattributes", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
public class TSOattributes {

    @XmlElement(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    protected java.util.List<Attribute> attribute;
    @XmlElement(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    protected java.util.List<com.cosmote.api.generic.xjc.List> list;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    public java.util.List<Attribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<Attribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the list property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cosmote.api.generic.xjc.List }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    public java.util.List<com.cosmote.api.generic.xjc.List> getList() {
        if (list == null) {
            list = new ArrayList<com.cosmote.api.generic.xjc.List>();
        }
        return this.list;
    }

}
