//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 10:06:28 AM EET 
//


package com.cosmote.api.generic.xjc;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOheader"/&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOattributes" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOresult" minOccurs="0"/&gt;
 *         &lt;element name="DELIVERY_CONTENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tsOheader",
    "tsOattributes",
    "tsOresult",
    "deliverycontent"
})
@XmlRootElement(name = "TSO_DATA", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
public class TSODATA {

    @XmlElement(name = "TSOheader", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    protected TSOheader tsOheader;
    @XmlElement(name = "TSOattributes", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    protected TSOattributes tsOattributes;
    @XmlElement(name = "TSOresult", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    protected TSOresult tsOresult;
    @XmlElement(name = "DELIVERY_CONTENT", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    protected String deliverycontent;

    /**
     * Gets the value of the tsOheader property.
     * 
     * @return
     *     possible object is
     *     {@link TSOheader }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public TSOheader getTSOheader() {
        return tsOheader;
    }

    /**
     * Sets the value of the tsOheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOheader }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public void setTSOheader(TSOheader value) {
        this.tsOheader = value;
    }

    /**
     * Gets the value of the tsOattributes property.
     * 
     * @return
     *     possible object is
     *     {@link TSOattributes }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public TSOattributes getTSOattributes() {
        return tsOattributes;
    }

    /**
     * Sets the value of the tsOattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOattributes }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public void setTSOattributes(TSOattributes value) {
        this.tsOattributes = value;
    }

    /**
     * Gets the value of the tsOresult property.
     * 
     * @return
     *     possible object is
     *     {@link TSOresult }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public TSOresult getTSOresult() {
        return tsOresult;
    }

    /**
     * Sets the value of the tsOresult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOresult }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public void setTSOresult(TSOresult value) {
        this.tsOresult = value;
    }

    /**
     * Gets the value of the deliverycontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public String getDELIVERYCONTENT() {
        return deliverycontent;
    }

    /**
     * Sets the value of the deliverycontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:27+02:00", comments = "JAXB RI v2.3.2")
    public void setDELIVERYCONTENT(String value) {
        this.deliverycontent = value;
    }

}
