//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.10 at 06:50:19 AM EEST 
//


package com.cosmote.api.generic.xjc;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="TSOID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TSOlabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="destinationSystemId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="destinationSystemPassword" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="inconcertTaskId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numberOfAttributes" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="continueOnFail" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rollbackOnError" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="actionReason" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="submitTSO" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orderId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IMSI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TSOheader", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
public class TSOheader {

    @XmlAttribute(name = "TSOID", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String tsoid;
    @XmlAttribute(name = "TSOlabel", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String tsOlabel;
    @XmlAttribute(name = "destinationSystemId")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String destinationSystemId;
    @XmlAttribute(name = "destinationSystemPassword")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String destinationSystemPassword;
    @XmlAttribute(name = "inconcertTaskId")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String inconcertTaskId;
    @XmlAttribute(name = "numberOfAttributes")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String numberOfAttributes;
    @XmlAttribute(name = "sequenceId")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String sequenceId;
    @XmlAttribute(name = "continueOnFail")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String continueOnFail;
    @XmlAttribute(name = "rollbackOnError")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String rollbackOnError;
    @XmlAttribute(name = "actionReason")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String actionReason;
    @XmlAttribute(name = "submitTSO")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String submitTSO;
    @XmlAttribute(name = "orderId")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String orderId;
    @XmlAttribute(name = "MSISDN")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String msisdn;
    @XmlAttribute(name = "IMSI")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String imsi;
    @XmlAttribute(name = "priority")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected Integer priority;

    /**
     * Gets the value of the tsoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getTSOID() {
        return tsoid;
    }

    /**
     * Sets the value of the tsoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setTSOID(String value) {
        this.tsoid = value;
    }

    /**
     * Gets the value of the tsOlabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getTSOlabel() {
        return tsOlabel;
    }

    /**
     * Sets the value of the tsOlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setTSOlabel(String value) {
        this.tsOlabel = value;
    }

    /**
     * Gets the value of the destinationSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getDestinationSystemId() {
        return destinationSystemId;
    }

    /**
     * Sets the value of the destinationSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setDestinationSystemId(String value) {
        this.destinationSystemId = value;
    }

    /**
     * Gets the value of the destinationSystemPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getDestinationSystemPassword() {
        return destinationSystemPassword;
    }

    /**
     * Sets the value of the destinationSystemPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setDestinationSystemPassword(String value) {
        this.destinationSystemPassword = value;
    }

    /**
     * Gets the value of the inconcertTaskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getInconcertTaskId() {
        return inconcertTaskId;
    }

    /**
     * Sets the value of the inconcertTaskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setInconcertTaskId(String value) {
        this.inconcertTaskId = value;
    }

    /**
     * Gets the value of the numberOfAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getNumberOfAttributes() {
        return numberOfAttributes;
    }

    /**
     * Sets the value of the numberOfAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setNumberOfAttributes(String value) {
        this.numberOfAttributes = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the continueOnFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getContinueOnFail() {
        return continueOnFail;
    }

    /**
     * Sets the value of the continueOnFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setContinueOnFail(String value) {
        this.continueOnFail = value;
    }

    /**
     * Gets the value of the rollbackOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getRollbackOnError() {
        return rollbackOnError;
    }

    /**
     * Sets the value of the rollbackOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setRollbackOnError(String value) {
        this.rollbackOnError = value;
    }

    /**
     * Gets the value of the actionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getActionReason() {
        return actionReason;
    }

    /**
     * Sets the value of the actionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setActionReason(String value) {
        this.actionReason = value;
    }

    /**
     * Gets the value of the submitTSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getSubmitTSO() {
        return submitTSO;
    }

    /**
     * Sets the value of the submitTSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setSubmitTSO(String value) {
        this.submitTSO = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setIMSI(String value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setPriority(Integer value) {
        this.priority = value;
    }

}
