//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.10 at 06:50:19 AM EEST 
//


package com.cosmote.api.generic.xjc;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}statusCode"/&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}errorCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}errorDescription" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusCode",
    "errorCode",
    "errorDescription"
})
@XmlRootElement(name = "TSOresult", namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
public class TSOresult {

    @XmlElement(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String statusCode;
    @XmlElement(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String errorCode;
    @XmlElement(namespace = "http://www.accenture.com/assets/sdp/commonDataModel/asynch")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    protected String errorDescription;

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Sets the value of the errorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-04-10T06:50:19+03:00", comments = "JAXB RI v2.3.2")
    public void setErrorDescription(String value) {
        this.errorDescription = value;
    }

}
