//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.29 at 08:13:36 PM EEST 
//


package com.cosmote.api.tutorial.xjc;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tutorials" type="{http://www.wstutorial.com/ws/TutorialService}TutorialType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tutorials"
})
@XmlRootElement(name = "getTutorialsResponse", namespace = "http://www.wstutorial.com/ws/TutorialService")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
public class GetTutorialsResponse {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    protected List<TutorialType> tutorials;

    /**
     * Gets the value of the tutorials property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tutorials property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTutorials().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TutorialType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-04-29T08:13:36+03:00", comments = "JAXB RI v2.3.2")
    public List<TutorialType> getTutorials() {
        if (tutorials == null) {
            tutorials = new ArrayList<TutorialType>();
        }
        return this.tutorials;
    }

}
