//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 10:06:29 AM EET 
//


package com.cosmote.api.tutorial.xjc;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tutorialType" type="{http://www.wstutorial.com/ws/TutorialService}TutorialType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tutorialType"
})
@XmlRootElement(name = "updateTutorialRequest", namespace = "http://www.wstutorial.com/ws/TutorialService")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:29+02:00", comments = "JAXB RI v2.3.2")
public class UpdateTutorialRequest {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:29+02:00", comments = "JAXB RI v2.3.2")
    protected TutorialType tutorialType;

    /**
     * Gets the value of the tutorialType property.
     * 
     * @return
     *     possible object is
     *     {@link TutorialType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:29+02:00", comments = "JAXB RI v2.3.2")
    public TutorialType getTutorialType() {
        return tutorialType;
    }

    /**
     * Sets the value of the tutorialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TutorialType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-11T10:06:29+02:00", comments = "JAXB RI v2.3.2")
    public void setTutorialType(TutorialType value) {
        this.tutorialType = value;
    }

}
