//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.28 at 04:13:21 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.cosmote.com/xml/employees", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cosmote.api.xjc;
